registry:
  # Plugin registry settings example
  url: 'https://github.com/{name}/{repository}/releases/download/{tag}'
  name: ''
  repository: ''
  tag: 'latest'
logging:
  # Setting the log level: CRITICAL, ERROR, WARNING, INFO, DEBUG
  level: 'DEBUG'
plugins:
  # Packages to download from registry
  - sample-plugin
  - FaceRecognition
  - Brightness
  - ImageQuality
  - EyesOpen
